### PR TITLE
use ListItem in DialogFile to have beatiful theme matcher

### PR DESCRIPTION
**Pull request by manland**
I'm working on https://github.com/ubports/ubuntu-touch/issues/1520 and I use dark theme... so I have done https://github.com/ubports/settings-components/issues/15 :joy: 

screenshot20200824_184601566
screenshot20200824_185106250

### CODE REVIEW

**Comment by Flohack74** [comment]
I target it for OTA-14, for this cycle we have already closed the commits ;)

**Comment by manland** [comment]
@Flohack74 thanks!

**Comment by Flohack74** [comment]
Sorry we missed this for OTA-14...

**Review by UniversalSuperBox — APPROVED** [review]
Looks excellent. Thank you very much!

**Pull request merged**
